// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	audit "github.com/CryptoGu1/books-grpc-log/pkg/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuditClient is an autogenerated mock type for the AuditClient type
type AuditClient struct {
	mock.Mock
}

// SendLogRequest provides a mock function with given fields: ctx, req
func (_m *AuditClient) SendLogRequest(ctx context.Context, req audit.LogItem) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendLogRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, audit.LogItem) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditClient creates a new instance of AuditClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditClient {
	mock := &AuditClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
